### ISSUE TITLE
corrupted archive

### ISSUE THREAD

**Issue by nobody00304** [soufianetahiri/Leaked-Password#1]
cannot open the files as [7z] archive unexpected end of data

**Comment by soufianetahiri** [comment]
It's a single file splited on parts. You need to download all parts.

**Comment by nobody00304** [comment]
> 
> 
> It's a single file splited on parts. You need to download all parts.

yes i did download all the parts.

**Comment by mbhound** [comment]
Even after combining files, it still says the 7z is corrupt
